### ISSUE TITLE
👋 hello from LightGBM

### ISSUE THREAD

**Issue by jameslamb** [sentinel-hub/sentinel2-cloud-detector#32] opened 2021-08-18 05:07 UTC
Hello from Chicago! My name is James, and I'm one of the maintainers of LightGBM.

@TomAugspurger told me about this project at the last Dask community meeting (https://github.com/dask/community/issues/174). I clicked through the documentation here today and was really excited to see LightGBM being used in this way!

I'm just opening this issue as an introduction and to let you know we're happy to help if you have LightGBM questions. If you ever run into any challenges and need some help, please ask at https://github.com/microsoft/LightGBM/issues.

If maintainers here are open to it, I'd also be happy to talk on a video call some time to meet each other, learn more about how you're using LightGBM, and tell you about what's coming in future releases. If that interests you, you can contact me at the email address in my profile here.

**Comment by AleksMat** [comment] 2021-08-18 17:29
Hi @jameslamb,

Thank you for reaching out. Besides this project we are actually using LightGBM quite a lot in our work with satellite data. It performs really well for various pixel-based classification and regression problems, such as [this one](https://eo-learn.readthedocs.io/en/latest/examples/land-cover-map/SI_LULC_pipeline.html). It is also a good alternative to neural nets as it requires less processing resources.

Recently, we have been working on upscaling our processes to Ray and Dask clusters. For this we are looking for best ways of running LightGBM inference in combination with Ray and Dask parallelization. In the near future we'll probably also look into parallelized training, which seems to be well covered in [`lightgbm_ray`](https://github.com/ray-project/lightgbm_ray) and [LightGBM docs about distributed learning](https://lightgbm.readthedocs.io/en/latest/Parallel-Learning-Guide.html).

Great job on maintaining such an amazing package and we'll let you know once we compose some concrete questions.

**Comment by jameslamb** [comment] 2021-08-18 17:35
Really exciting!

If you're interested in distributed learning, near the end of 2020 we merged `dask-lightgbm` into the `lightgbm` Python package, so we now have first-class support for Dask. You can read about it here: https://lightgbm.readthedocs.io/en/latest/Parallel-Learning-Guide.html#dask.

There has been a lot of work on the Dask integration since the last release, so you may also want to subscribe to https://github.com/microsoft/LightGBM/issues/4310 to be notified when v3.3.0 is out.

Cheers and have a great week!

**Comment by AleksMat** [comment] 2021-08-19 07:42
Thanks for the info and I'll be looking forward to v3.3.0. :smiley: 

I'm closing this issue for now but feel free to reopen anytime.

**Closed by AleksMat** 2021-08-19 07:42 UTC
